### ISSUE TITLE
Updating lib to 0.12.5

### ISSUE THREAD

**Issue by AmirMingaliev** [nicholasklick/wkhtmltoimage-binary#12]
Hi @nicholasklick and thank you for your work on this gem!

There is an issue when tmp files don't be deleted after execution `wkhtmltoimage` in 0.12.4 version. So this problem takes huge part of memory on production. Here is the link to the issue: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1981#issuecomment-362886728. It seems that it was resolved and fixed in the latest 0.12.5 version.

Could we please update the version of binaries to 0.12.5? I probably can do it by myself and create PR, but I'm not sure where and which binaries I should get.

Thanks in advance.

**Comment by phackwer** [comment]
I was about to open same request. :D

**Comment by nicholasklick** [comment]
I will take a look at this tonight and see what the options are. Sorry for the delay!

**Comment by AmirMingaliev** [comment]
Hi @nicholasklick! What's the status of this issue?

**Comment by nicholasklick** [comment]
Hi @AmirMingaliev, sorry for the delay. Pulling all the binaries out of the packages has proved a bit annoying. If you have time to pull some from here https://wkhtmltopdf.org/downloads.html and create a PR that works for me also. I just downloaded all the 64bit packages.

**Comment by AmirMingaliev** [comment]
@nicholasklick okay, I will prepare a PR

**Comment by AmirMingaliev** [comment]
Hi @nicholasklick @phackwer. While testing I have found that issue wasn't fixed for `wkhtmltoimage` lib and seems fix works only for `wkhtmltopdf`. I have created separate issue: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4003, but anyway I will update the binaries since I almost did the work.

**Comment by malaproping** [comment]
Fixed via https://github.com/nicholasklick/wkhtmltoimage-binary/pull/13

**Comment by malaproping** [comment]
`0.12.5` was pushed to rubygems today also.

**Comment by bugg2844** [comment]
Hi,

0.12.5 doesn't seem to be on rubygems, only 0.12.4.

**Comment by malaproping** [comment]
@bugg2844 Where are seeing that?

I see this: https://rubygems.org/gems/wkhtmltoimage-binary/versions/0.12.5

Also, I just tested a new project:
```
Gemfile:
source 'https://rubygems.org'
gem 'wkhtmltoimage-binary'

$ bundle
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 1.17.1
Fetching wkhtmltoimage-binary 0.12.5
Installing wkhtmltoimage-binary 0.12.5
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
$ bundle exec gem list

*** LOCAL GEMS ***

bundler (1.17.1)
wkhtmltoimage-binary (0.12.5)
```

**Comment by bugg2844** [comment]
Sorry, I was looking at to PDF.

**Comment by malaproping** [comment]
No worries.
