### ISSUE TITLE
wkhtmltoimage-amd64 does not work on Heroku

### ISSUE THREAD

**Issue by bhanuprasad143** [nicholasklick/wkhtmltoimage-binary#4]
I cannot get this binary worked on Heroku. My older version (~10MB file) worked fine before the upgrade to this version.

   imgkit (1.6.0)

IMGKit::CommandFailedError: Command failed: /app/bin/wkhtmltoimage-amd64 --height 595 --quality 100 --width 420 --format png - -: /app/bin/wkhtmltoimage-amd64: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory

**Comment by nicholasklick** [comment]
Sorry for the slow reply. For some reason I didnt receive a notification for this issue. I will investigate and get back to you! Unless you already figured it out?

**Comment by nicholasklick** [comment]
You still having trouble with this? Feel free to reopen the issue if so.
