### ISSUE TITLE
Not working in Debian 8 (Jessie)

### ISSUE THREAD

**Issue by jrodrigosm** [nicholasklick/wkhtmltoimage-binary#5]
Hi,

I installed this gem, as a companion to the 'imgkit' gem. The point of installing the gem is that, when deploying to Heroku, the wkhtmltoimage dependency is intalled automatically (therefore removing the need to use a custom buildpack). In Heroku Cedar-14 (which uses Ubuntu 14.04), everything works well.

However we also need to run our app in a Debian Jessie server ... and that's when we run into problems: the wkhtmltoimage binary provided by the gem is compiled against libjpeg8, but Debian Jessie lacks the libjpeg8 library. Therefore the code halts when calling wkhtmltoimage.

Any thoughts on how to make this work under Debian Jessie, while keeping the same Gemfile that I use for Heroku?

Also, maybe the README should be updated to reflect this?

**Comment by nicholasklick** [comment]
What version of libjpeg is installed by default on Jessie?

**Comment by jrodrigosm** [comment]
Jessie uses libjpeg62-turbo (and libjpeg62-turbo-dev)

**Comment by nicholasklick** [comment]
Can you compile wkhtmltoimage on Debian Jessie manually and then post the binary somewhere for me to download. Then I will either update this gem to support it or create a new edge gem with the latest binaries.

**Comment by jrodrigosm** [comment]
Here you are: https://www.dropbox.com/s/k8r2985oqhh23rn/wkhtmltoimage?dl=0 (link expires in 7 days)

Btw, I did not compile the file from source, I just extracted the wkhtmltoimage binary from the official jessie binary package. For the record, this is what I did, so that you can do it if you want to extract the binary yourself:

    wget http://downloads.sourceforge.net/wkhtmltopdf/wkhtmltox-0.12.2.1_linux-jessie-amd64.deb
    ar x wkhtmltox-0.12.2.1_linux-jessie-amd64.deb data.tar.xz
    tar xf data.tar.xz ./usr/local/bin/wkhtmltoimage --strip-components 4

**Comment by nicholasklick** [comment]
So that binary is massive for some reason, not sure I can support yet another linux version since Ubuntu is pretty much standard for app servers etc. Feel free to fork the gem and create a wkhtmltoimage-debian and you should be good.

**Comment by nicholasklick** [comment]
FYI, a PR came in to support Debian Jessie.

https://github.com/nicholasklick/wkhtmltoimage-binary/commit/5be9d5d42fd45346931524dc924349e8f1af5f8c
