### ISSUE TITLE
Doesn't work on Mac

### ISSUE THREAD

**Issue by rush-skills** [nicholasklick/wkhtmltoimage-binary#8]
Machine: Mac Pro 13 Retina (Early 2015 model)
OS: Mac OS X El Capitan 10.11.4 (64 bit)
Gem version: 0.12.2

Tried running, gave an error

```
Sorry, I couldn't find the binary for your architecture (OSX) 
  at http://code.google.com/p/wkhtmltopdf/downloads/list?can=1
Please go to that page, unzip the appropriate binary, and install
```

**Comment by nicholasklick** [comment]
Thanks for the heads up. I will either upgrade the current gem or create a new edge gem.

**Comment by nicholasklick** [comment]
Did you get this working?

**Comment by rush-skills** [comment]
I used the latest release from http://wkhtmltopdf.org/downloads.html to get it working, install using this gem didn't work.

**Comment by malaproping** [comment]
This shouldnt be relevant anymore as the gem has been upgraded.
